version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: claim_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: new_employee_db
    ports:
      - "5408:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./Backend
    container_name: claim_backend
    ports:
      - "3407:3407"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./Backend/Uploads:/app/Uploads
    command: ["node", "server.js"]

  frontend:
    build: ./Frontend
    container_name: claim_frontend
    ports:
      - "8027:80"
    networks:
      - app-network

  hr_page:
    build: ./HR_Page
    container_name: claim_hrpage
    ports:
      - "8028:80"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge

